spring:
  application:
    name: AI Assistant Demo
  profiles:
    active: gemini   # switch to 'gemini' or 'ollama' when needed

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG